import React,{useEffect,useMemo,useState}from'react';
import{Alert,Linking,NativeModules,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from'react-native';
type Usage={packageName:string;appName:string;minutes:number};
const{MaTimerUsage}=NativeModules;
const demo:Usage[]=[{packageName:'youtube',appName:'YouTube',minutes:108},{packageName:'instagram',appName:'Instagram',minutes:72},{packageName:'whatsapp',appName:'WhatsApp',minutes:36},{packageName:'chrome',appName:'Chrome',minutes:22}];
const fm=(m:number)=>Math.floor(m/60)+'h '+m%60+'m';
export default function Index(){
const[tab,setTab]=useState('Home');const[apps,setApps]=useState<Usage[]>(demo);const[granted,setGranted]=useState(false);const[sec,setSec]=useState(1500);const[running,setRunning]=useState(false);
const total=useMemo(()=>apps.reduce((x,a)=>x+a.minutes,0),[apps]);
useEffect(()=>{let live=true;(async()=>{if(!MaTimerUsage?.hasUsageAccess)return;const ok=await MaTimerUsage.hasUsageAccess();if(!live)return;setGranted(ok);if(ok){const d=await MaTimerUsage.getTodayUsage();if(live&&Array.isArray(d)){d.sort((a:Usage,b:Usage)=>b.minutes-a.minutes);setApps(d.slice(0,8));}}})();return()=>{live=false}},[]);
useEffect(()=>{if(!running)return;const id=setInterval(()=>setSec(x=>{if(x<=1){clearInterval(id);setRunning(false);Alert.alert('Focus complete','Your focus session is finished.');return 0}return x-1}),1000);return()=>clearInterval(id)},[running]);
const open=async()=>{try{if(MaTimerUsage?.openUsageAccessSettings)await MaTimerUsage.openUsageAccessSettings();else await Linking.openSettings()}catch{Alert.alert('Usage Access','Enable Ma Timer in Android Usage Access settings.')}};
const timer=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');
const home=<ScrollView contentContainerStyle={s.content}><View style={s.head}><Text style={s.brand}>Ma <Text style={s.green}>Timer</Text></Text><Text style={s.gear}>⚙</Text></View><View style={s.hero}><Text style={s.phone}>◉</Text><Text style={s.heroText}>if you uninstall this{'
'}nothing going to change</Text></View>{!granted&&<Pressable style={s.permission} onPress={open}><Text style={s.white}>Enable real app usage</Text><Text style={s.muted}>Allow Usage Access to read today's Android screen-time.</Text><Text style={s.green}>OPEN SETTINGS →</Text></Pressable>}<View style={s.stats}><View style={s.stat}><Text style={s.muted}>Today's Usage</Text><Text style={s.value}>{fm(total)}</Text><Text style={s.green}>{granted?'Live data':'Demo data'}</Text></View><View style={s.stat}><Text style={s.muted}>Daily Target</Text><Text style={s.value}>3h 0m</Text><Text style={s.green}>{Math.min(100,Math.round(total/180*100))}%</Text></View></View><Text style={s.section}>Top Apps</Text><View style={s.card}>{apps.slice(0,4).map((a,i)=><View style={s.row} key={a.packageName}><Text style={s.icon}>{['▶','◎','◉','◌'][i]}</Text><Text style={s.app}>{a.appName}</Text><Text style={s.time}>{fm(a.minutes)}</Text></View>)}</View><View style={s.quote}><Text style={s.white}>💡 Less phone, more life.</Text><Text style={s.muted}>You can do better!</Text></View></ScrollView>;
const page=tab==='Home'?home:tab==='Apps'?<ScrollView contentContainerStyle={s.content}><Text style={s.title}>Apps</Text><View style={s.card}>{apps.map(a=><View style={s.row} key={a.packageName}><Text style={s.icon}>●</Text><Text style={s.app}>{a.appName}</Text><Text style={s.time}>{fm(a.minutes)}</Text></View>)}</View></ScrollView>:tab==='Timer'?<ScrollView contentContainerStyle={s.center}><Text style={s.title}>Focus Timer</Text><View style={s.ring}><Text style={s.timer}>{timer}</Text><Text style={s.muted}>Focus Time</Text></View><Pressable style={s.start} onPress={()=>setRunning(!running)}><Text style={s.startText}>{running?'Pause':'Start'}</Text></Pressable><View style={s.choices}>{[25,45,60].map(m=><Pressable key={m} style={s.choice} onPress={()=>{setRunning(false);setSec(m*60)}}><Text style={s.white}>{m} min</Text></Pressable>)}</View></ScrollView>:tab==='Trend'?<ScrollView contentContainerStyle={s.content}><Text style={s.title}>Trend</Text><View style={s.card}><Text style={s.muted}>Screen Time Today</Text><Text style={s.big}>{fm(total)}</Text><Text style={s.green}>Live from Android Usage Access</Text></View></ScrollView>:<ScrollView contentContainerStyle={s.content}><Text style={s.title}>Settings</Text><Pressable style={s.setting} onPress={open}><Text style={s.white}>App Usage</Text><Text style={s.muted}>›</Text></Pressable><View style={s.hero}><Text style={s.heroText}>if you uninstall this{'
'}nothing going to change</Text></View><Text style={s.muted}>Ma Timer 1.0.0</Text></ScrollView>;
return <SafeAreaView style={s.safe}>{page}<View style={s.nav}>{['Home','Apps','Timer','Trend','More'].map(x=><Pressable key={x} onPress={()=>setTab(x)}><Text style={[s.navText,tab===x&&s.green]}>{x}</Text></Pressable>)}</View></SafeAreaView>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#020a12'},content:{padding:18,paddingBottom:90},center:{padding:18,paddingBottom:100,alignItems:'center'},head:{flexDirection:'row',justifyContent:'space-between',marginBottom:18},brand:{fontSize:25,fontWeight:'800',color:'#fff'},gear:{fontSize:24,color:'#fff'},green:{color:'#18e0ab'},white:{color:'#fff',fontWeight:'700'},muted:{color:'#91a3af',marginTop:4},hero:{backgroundColor:'#063b3c',borderRadius:22,padding:24,alignItems:'center',marginBottom:14},phone:{fontSize:28,color:'#18e0ab'},heroText:{fontSize:21,fontWeight:'800',textAlign:'center',color:'#fff',lineHeight:28},permission:{backgroundColor:'#09222b',borderRadius:18,padding:16,marginBottom:14,borderWidth:1,borderColor:'#116c6b'},stats:{flexDirection:'row',gap:10,marginBottom:20},stat:{flex:1,backgroundColor:'#071725',borderRadius:15,padding:14},value:{fontSize:18,fontWeight:'800',color:'#fff',marginTop:8},section:{fontSize:18,fontWeight:'800',color:'#fff',marginBottom:10},card:{backgroundColor:'#061521',borderRadius:16,paddingHorizontal:14,borderWidth:1,borderColor:'#102b3b'},row:{flexDirection:'row',alignItems:'center',paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#10232f'},icon:{width:30,color:'#18e0ab',fontSize:18},app:{flex:1,color:'#e9f0f4'},time:{color:'#b9c6ce'},quote:{backgroundColor:'#063537',borderRadius:16,padding:18,marginTop:16},title:{fontSize:24,fontWeight:'800',color:'#fff',marginBottom:18},ring:{width:250,height:250,borderRadius:125,borderWidth:18,borderColor:'#18e0ab',alignItems:'center',justifyContent:'center',marginTop:25},timer:{fontSize:44,fontWeight:'800',color:'#fff'},start:{marginTop:30,width:'90%',backgroundColor:'#18e0ab',borderRadius:30,padding:18,alignItems:'center'},startText:{fontSize:18,fontWeight:'900',color:'#00130f'},choices:{flexDirection:'row',gap:10,marginTop:22},choice:{borderWidth:1,borderColor:'#1d3b4f',borderRadius:15,padding:16},big:{fontSize:34,fontWeight:'900',color:'#fff',marginVertical:8},setting:{flexDirection:'row',justifyContent:'space-between',padding:18,borderBottomWidth:1,borderBottomColor:'#112533'},nav:{position:'absolute',left:0,right:0,bottom:0,height:64,backgroundColor:'#04111b',borderTopWidth:1,borderTopColor:'#123040',flexDirection:'row',justifyContent:'space-around',alignItems:'center'},navText:{color:'#91a3af',fontSize:12}});
