import 'dart:async';
import 'package:flutter/material.dart';
import 'package:usage_stats/usage_stats.dart';
const bg=Color(0xFF090D0E),card=Color(0xFF121A1C),accent=Color(0xFF00E676),muted=Color(0xFF8A9698);
void main(){WidgetsFlutterBinding.ensureInitialized();runApp(const App());}
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(title:'Ma Timer',debugShowCheckedModeBanner:false,theme:ThemeData(brightness:Brightness.dark,scaffoldBackgroundColor:bg,useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:accent,brightness:Brightness.dark)),home:const Shell());}
class Shell extends StatefulWidget{const Shell({super.key});@override State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int tab=0;@override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_){try{UsageStats.grantUsagePermission();}catch(_){}});}@override Widget build(BuildContext c){const pages=[Home(),Apps(),TimerPage(),Trend(),More()];return Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(backgroundColor:const Color(0xFF0C1112),selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'Home'),NavigationDestination(icon:Icon(Icons.apps_outlined),label:'Apps'),NavigationDestination(icon:Icon(Icons.timer_outlined),label:'Timer'),NavigationDestination(icon:Icon(Icons.insights_outlined),label:'Trend'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'More')]));}}
class Frame extends StatelessWidget{final Widget child;const Frame({super.key,required this.child});@override Widget build(BuildContext c)=>SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:child));}
class Header extends StatelessWidget{const Header({super.key});@override Widget build(BuildContext c)=>Row(children:[const Text('Ma Timer',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Spacer(),IconButton(onPressed:(){},icon:const Icon(Icons.workspace_premium,color:accent)),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())),icon:const Icon(Icons.settings_outlined))]);}
class Notice extends StatelessWidget{const Notice({super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFF1A2527),borderRadius:BorderRadius.circular(14)),child:const Row(children:[Icon(Icons.info_outline,color:accent),SizedBox(width:10),Expanded(child:Text('if you uninstall this nothing going to change',style:TextStyle(fontWeight:FontWeight.w600)))]));}
class Stat extends StatelessWidget{final String a,b,c;final double? p;const Stat(this.a,this.b,this.c,{this.p,super.key});@override Widget build(BuildContext x)=>Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:muted)),const SizedBox(height:6),Row(children:[Text(b,style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const Spacer(),Text(c,style:const TextStyle(color:accent))]),if(p!=null)...[const SizedBox(height:10),LinearProgressIndicator(value:p,color:accent)]]));}
class AppRow extends StatelessWidget{final String n,t,p;final IconData i;const AppRow(this.n,this.t,this.p,this.i,{super.key});@override Widget build(BuildContext c)=>Card(color:card,child:ListTile(leading:CircleAvatar(backgroundColor:const Color(0xFF1E292B),child:Icon(i,color:accent)),title:Text(n,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(t),trailing:Text(p,style:const TextStyle(color:muted))));}
List<Widget> rows()=>const[AppRow('YouTube','1h 48m','39%',Icons.play_circle_fill),AppRow('Instagram','1h 12m','26%',Icons.camera_alt),AppRow('WhatsApp','36m','13%',Icons.chat),AppRow('Chrome','22m','8%',Icons.public),AppRow('Telegram','16m','6%',Icons.send),AppRow('Other Apps','18m','8%',Icons.grid_view)];
class Home extends StatelessWidget{const Home({super.key});@override Widget build(BuildContext c)=>Frame(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Header(),const SizedBox(height:14),const Notice(),const SizedBox(height:16),Row(children:[const Expanded(child:Stat('Today','4h 32m','↑ 12%')),const SizedBox(width:10),const Expanded(child:Stat('Unlocks','78','↑ 18%'))]),const SizedBox(height:10),const Stat('Target','3h 0m','',p:.72),const SizedBox(height:20),const Text('Top Apps',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...rows()]));}
class Apps extends StatelessWidget{const Apps({super.key});@override Widget build(BuildContext c)=>Frame(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Apps',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:14),const Notice(),const SizedBox(height:18),...rows()]));}
class TimerPage extends StatefulWidget{const TimerPage({super.key});@override State<TimerPage> createState()=>_TimerState();}
class _TimerState extends State<TimerPage>{int total=1500,left=1500;Timer? timer;bool running=false;void pick(int m){timer?.cancel();setState((){total=m*60;left=total;running=false;});}void toggle(){if(running){timer?.cancel();setState(()=>running=false);}else{setState(()=>running=true);timer=Timer.periodic(const Duration(seconds:1),(_){if(left==0){timer?.cancel();setState(()=>running=false);}else setState(()=>left--);});}}@override void dispose(){timer?.cancel();super.dispose();}@override Widget build(BuildContext c){final mm=(left/60).floor().toString().padLeft(2,'0'),ss=(left%60).toString().padLeft(2,'0');return Frame(child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('Focus Timer',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900))),const SizedBox(height:24),SizedBox(width:260,height:260,child:Stack(alignment:Alignment.center,children:[SizedBox(width:245,height:245,child:CircularProgressIndicator(value:total==left ? .04 : 1-left/total,strokeWidth:12,color:accent,backgroundColor:const Color(0xFF283537))),Text(mm+':'+ss,style:const TextStyle(fontSize:42,fontWeight:FontWeight.w900))])),const Text('Focus Time',style:TextStyle(color:muted)),const SizedBox(height:28),SizedBox(width:double.infinity,height:56,child:FilledButton.icon(onPressed:toggle,icon:Icon(running?Icons.pause:Icons.play_arrow),label:Text(running?'Pause':'Start'),style:FilledButton.styleFrom(backgroundColor:accent,foregroundColor:Colors.black))),const SizedBox(height:14),Wrap(spacing:8,children:[OutlinedButton(onPressed:()=>pick(25),child:const Text('25 min')),OutlinedButton(onPressed:()=>pick(45),child:const Text('45 min')),OutlinedButton(onPressed:()=>pick(60),child:const Text('60 min')),OutlinedButton(onPressed:()=>pick(30),child:const Text('⚙ Custom'))]) ]));}}
class Trend extends StatelessWidget{const Trend({super.key});@override Widget build(BuildContext c)=>Frame(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Trend',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:18),const Text('4h 32m',style:TextStyle(fontSize:34,fontWeight:FontWeight.w900)),const Text('↑ 12% than yesterday',style:TextStyle(color:accent)),const SizedBox(height:20),Container(height:260,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(18)),child:const Chart()),const SizedBox(height:16),const Card(color:card,child:ListTile(leading:Icon(Icons.lightbulb_outline,color:accent),title:Text('Less phone, more life. You can do better!')))]));}
class Chart extends StatelessWidget{const Chart({super.key});@override Widget build(BuildContext c){const v=[.5,.7,.4,.85,.6,.9,.75],d=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];return Row(crossAxisAlignment:CrossAxisAlignment.end,children:[for(int i=0;i<7;i++)Expanded(child:Column(children:[Expanded(child:Align(alignment:Alignment.bottomCenter,child:FractionallySizedBox(heightFactor:v[i],widthFactor:.42,child:DecoratedBox(decoration:BoxDecoration(color:accent,borderRadius:BorderRadius.circular(7)))))),Text(d[i],style:const TextStyle(fontSize:11,color:muted))]))]);}}
class More extends StatelessWidget{const More({super.key});@override Widget build(BuildContext c)=>Frame(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('More',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:14),const Notice(),const SizedBox(height:18),Menu(Icons.eco,'Focus Mode','Reduce distractions',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const FocusModePage()))),Menu(Icons.settings,'Settings','App preferences and permissions',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())))]));}
class Menu extends StatelessWidget{final IconData i;final String t,s;final VoidCallback? f;const Menu(this.i,this.t,this.s,this.f,{super.key});@override Widget build(BuildContext c)=>Card(color:card,child:ListTile(onTap:f,leading:Icon(i,color:accent),title:Text(t),subtitle:Text(s),trailing:const Icon(Icons.chevron_right)));}
class FocusModePage extends StatelessWidget{const FocusModePage({super.key});@override Widget build(BuildContext c)=>Frame(child:Column(children:[const Text('Focus Mode',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:20),const Card(color:card,child:Padding(padding:EdgeInsets.all(26),child:Column(children:[Icon(Icons.eco,size:80,color:accent),Text('Focus without distractions',style:TextStyle(fontSize:21,fontWeight:FontWeight.bold)),Text('Choose what Ma Timer should manage during focus sessions.',textAlign:TextAlign.center,style:TextStyle(color:muted))]))),const Menu(Icons.block,'Block Apps','Choose distracting apps',null),const Menu(Icons.schedule,'Schedule','Automate focus sessions',null),const Menu(Icons.tune,'Exceptions','Allow important apps',null),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){},child:const Text('Set Up')))]));}
class SettingsPage extends StatelessWidget{const SettingsPage({super.key});@override Widget build(BuildContext c)=>Frame(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Settings',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SetTile(Icons.insights,'Usage Access','Required for screen-time statistics'),const SetTile(Icons.notifications,'Notifications','Timer and focus reminders'),const SetTile(Icons.dark_mode,'Appearance','Dark mode'),const SetTile(Icons.lock,'Focus Protection','Manage focus restrictions'),const SetTile(Icons.timer,'Default Timer','25 minutes'),const SetTile(Icons.language,'Language','System default'),const SetTile(Icons.info,'About Ma Timer','Version 1.0.0'),const SizedBox(height:12),const Notice()]));}
class SetTile extends StatelessWidget{final IconData i;final String t,s;const SetTile(this.i,this.t,this.s,{super.key});@override Widget build(BuildContext c)=>Card(color:card,child:ListTile(leading:Icon(i,color:accent),title:Text(t),subtitle:Text(s),trailing:const Icon(Icons.chevron_right)));}
